[package]
name = "rust_src"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse = "0"
num = "0"
regex = "1"
ndarray = "0"

# [[bin]]
# name = "day_1"
# path = "src/day_1.rs"
